name: Backend CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./pub-sub-project

      - name: Run Lint
        run: npm run lint
        working-directory: ./pub-sub-project

      - name: Run Tests
        run: npm test
        working-directory: ./pub-sub-project

      - name: Build Project
        run: npm run build
        working-directory: ./pub-sub-project