services:
  # Redis 서비스 정의
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    platform: linux/amd64  # x86 플랫폼에 맞추기
    command: ["redis-server"] #, "/opt/homebrew/etc/redis.conf"
  
  #Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis-server
    ports:
      - "8081:8081"
    depends_on:
      - redis
    platform: linux/amd64  # x86 플랫폼에 맞추기

  #Nest.js 서비스 정의
  nest-app:
    build:
      context: ./pub-sub-project
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "4000:4000"
    environment:
      - "NODE_ENV=development"
    depends_on:
      - redis
    volumes:
      - ./pub-sub-project:/pub-subproject

  #React 서비스 정의
  react-app:
    build: 
      context: ./chat-app
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - nest-app
    volumes:
      - ./chat-app:/chat-app

volumes:
  redis-data:
    driver: local
